name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' or your default branch

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true

      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Build with Trunk
        run: |
          trunk build --release --public-url /${{ github.event.repository.name }}/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist